#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server
# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAproxy
sudo apt install -y haproxy

# Configure HAproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor 
    server 167962-web-01 54.160.123.73:80 check
    server 167962-web-02 52.3.252.23:80 check
EOF

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart

