#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg
sudo chmod 777 /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 167962-web-01 18.234.168.222:80 check
    server 167962-web-02 52.205.165.179:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

