#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
service nginx stop
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
rm -rf /var/log/nginx
mkdir /var/log/nginx
chown -R nginx:nginx /var/log/nginx
service nginx start

